save_best: false
base_dir: "${gym_env.env_name}/td3-S${algorithm.seed}_${current_time:}"
collect_stats: true
plot_agents: true
algorithm:
  max_grad_norm: 0.5
  epsilon: 0.02
  n_envs: 1
  n_steps: 100
  nb_evals: 10
  discount_factor: 0.98
  buffer_size: 200000
  batch_size: 64
  tau_target: 0.05
  eval_interval: 2000
  max_epochs: 11000
  learning_starts: 10000
  action_noise: 0.1
  architecture:
    actor_hidden_size: [400, 300]
    critic_hidden_size: [400, 300]
gym_env:
  env_name: "LunarLanderContinuous-v2"
actor_optimizer:
  classname: "torch.optim.Adam"
  lr: 0.001
critic_optimizer:
  classname: "torch.optim.Adam"
  lr: 0.001
